# Generated by Django 3.0.7 on 2020-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_notes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='label',
            field=models.TextField(max_length=200),
        ),
    ]
